const CREATED = 201;
const UNCORRECT_DATA = 400;
const UNAUTHORIZED = 401;
const DATA_NOT_FOUND = 404;
const DEFAULT_ERROR = 500;

module.exports = {
  CREATED, UNCORRECT_DATA, UNAUTHORIZED, DATA_NOT_FOUND, DEFAULT_ERROR,
};
